language: node_js
node_js:
  - 8

script:
  - yarn
  - yarn build
  - yarn test
  - yarn lint

# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: always